/**
 * Data access layer.
 * JSON datasets are generated by scripts/generate-data.mjs (runs automatically
 * before `dev` and `build` via the predev/prebuild npm hooks).
 */
import doctorsJson from "@/data/doctors.json";
import hospitalsJson from "@/data/hospitals.json";
import labsJson from "@/data/labs.json";
import ambulancesJson from "@/data/ambulances.json";
import type { AmbulanceService, Doctor, Hospital, Lab } from "./types";

export const doctors = doctorsJson as unknown as Doctor[];
export const hospitals = hospitalsJson as unknown as Hospital[];
export const labs = labsJson as unknown as Lab[];
export const ambulances = ambulancesJson as unknown as AmbulanceService[];

export const CITIES = [
  { name: "Mumbai", lat: 19.076, lng: 72.8777 },
  { name: "Delhi", lat: 28.6139, lng: 77.209 },
  { name: "Bengaluru", lat: 12.9716, lng: 77.5946 },
  { name: "Hyderabad", lat: 17.385, lng: 78.4867 },
  { name: "Chennai", lat: 13.0827, lng: 80.2707 },
  { name: "Kolkata", lat: 22.5726, lng: 88.3639 },
  { name: "Pune", lat: 18.5204, lng: 73.8567 },
  { name: "Ahmedabad", lat: 23.0225, lng: 72.5714 },
] as const;

export type CityName = (typeof CITIES)[number]["name"];

export const SPECIALTIES = Array.from(
  new Map(doctors.map((d) => [d.specialtyKey, { key: d.specialtyKey, name: d.specialty, hi: d.specialtyHi }])).values()
).sort((a, b) => a.name.localeCompare(b.name));

/** Haversine distance in km, rounded to 1 decimal. */
export function distanceKm(aLat: number, aLng: number, bLat: number, bLng: number): number {
  const R = 6371;
  const dLat = ((bLat - aLat) * Math.PI) / 180;
  const dLng = ((bLng - aLng) * Math.PI) / 180;
  const s =
    Math.sin(dLat / 2) ** 2 +
    Math.cos((aLat * Math.PI) / 180) * Math.cos((bLat * Math.PI) / 180) * Math.sin(dLng / 2) ** 2;
  return Math.round(R * 2 * Math.atan2(Math.sqrt(s), Math.sqrt(1 - s)) * 10) / 10;
}

export const formatINR = (n: number) => `₹${n.toLocaleString("en-IN")}`;

export const getDoctor = (id: string) => doctors.find((d) => d.id === id);
export const getHospital = (id: string) => hospitals.find((h) => h.id === id);
export const getLab = (id: string) => labs.find((l) => l.id === id);

/**
 * Ranking used across search results.
 * IMPORTANT (monetization transparency): Featured providers are boosted within
 * results but are ALWAYS visually labeled "Featured". Sorting explicitly chosen
 * by the user (price / rating / distance) is NEVER altered by Featured status —
 * paid placement only affects the default "Relevance" order.
 */
export function relevanceSort<T extends { featured: boolean; rating: number; reviewCount: number }>(list: T[]): T[] {
  return [...list].sort((a, b) => {
    if (a.featured !== b.featured) return a.featured ? -1 : 1;
    if (b.rating !== a.rating) return b.rating - a.rating;
    return b.reviewCount - a.reviewCount;
  });
}

/** Union list of all bookable diagnostic tests across labs (deduped, cheapest price shown). */
export function allTests(): { name: string; minPrice: number; labCount: number }[] {
  const map = new Map<string, { name: string; minPrice: number; labCount: number }>();
  for (const lab of labs) {
    for (const t of lab.tests) {
      const cur = map.get(t.name);
      if (!cur) map.set(t.name, { name: t.name, minPrice: t.price, labCount: 1 });
      else {
        cur.minPrice = Math.min(cur.minPrice, t.price);
        cur.labCount++;
      }
    }
  }
  return Array.from(map.values()).sort((a, b) => a.name.localeCompare(b.name));
}
